version: "3.7"
services:
  dekoratoren:
    container_name: dekoratoren
    image: "docker.pkg.github.com/navikt/nav-dekoratoren/nav-dekoratoren:latest"
    ports:
      - "8100:8088"
    environment:
      ENV: "localhost"
      XP_BASE_URL: "http://localhost:3000"
      APP_BASE_URL: "http://localhost:8100"
      APP_BASE_PATH: "/dekoratoren"
      API_XP_SERVICES_URL: "https://www.nav.no/_/service"
      API_UNLEASH_PROXY_URL: "https://www.nav.no/person/pb-unleash-proxy"
      API_INNLOGGINGSLINJE_URL: "http://localhost:8095/innloggingsstatus"
      API_VARSELINNBOKS_URL: "http://mocks:8080/person/varselinnboks"
      MINSIDE_ARBEIDSGIVER_URL: "http://localhost:8080/min-side-arbeidsgiver/"
      DITT_NAV_URL: "http://localhost:8080/person/dittnav/"
      LOGIN_URL: "http://localhost:5000"
      LOGOUT_URL: "http://localhost:5000/?logout"

volumes:
  event-cache-data:
